baseURL = 'https://quotes.arsh.wtf/'
languageCode = 'en-us'
title = "Arsh's Fav Quotes"
theme = "paper"
contentDir = "content"
monoDarkIcon = true
name = 'Arsh Sharma'
twitter = 'RinkiyaKeDad'
paginate = 5